# prometheus.yml
scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.8.11:9100', '192.168.8.1:9100']

  - job_name: OpenWrt
    static_configs:
      - targets: ['192.168.8.1:9100']
